const router = require("express").Router();
const rencontreController=require("../controller/rencontre.controller");
router.put("/activite-compte/:id",rencontreController.ActiviteCompte)
router.put("/infogenerale/domainepro/:id",rencontreController.InfoGeneraleDomainePro)
router.put("/infogenerale/age/:id",rencontreController.InfoGeneraleAge)
router.put("/infogenerale/genre/:id",rencontreController.InfoGeneraleGenre)
router.put("/infogenerale/orientationsexe/:id",rencontreController.InfoGeneraleOrientationSexuelle)
router.put("/infogenerale/origine/:id",rencontreController.InfoGeneraleOrigine)
router.put("/infogenerale/signezodiacale/:id",rencontreController.InfoGeneraleSigneZodiacale)
router.put("/localisation/rayon/:id",rencontreController.LocalisationRayon)
router.put("/localisation/localite/:id",rencontreController.LocalisationLocalite)
router.put("/valeurs-recherches/valeurs/:id",rencontreController.ValeursEtRecherchesValeures)
router.put("/valeurs-recherches/relatiions/:id",rencontreController.ValeursEtRecherchesRelations)
router.put("/apparence/taille/:id",rencontreController.ApparenceTaille)
router.put("/apparence/silhouette/:id",rencontreController.ApparenceSilhouette)
router.put("/apparence/yeux/:id",rencontreController.ApparenceYeux)
router.put("/apparence/cheveux/:id",rencontreController.ApparenceCheveux)
router.put("/apparence/pilositecorporelle/:id",rencontreController.ApparencePilositeCorporelle)
router.put("/apparence/pilositefaciale/:id",rencontreController.ApparencePilositeFaciale)
router.put("/detailsphysique/tatouage/:id",rencontreController.DetailsPhysiqueTatouage)
router.put("/detailsphysique/piercingcorporel/:id",rencontreController.DetailsPhysiquePiercingCorporel)
router.put("/detailsphysique/piercingfaciale/:id",rencontreController.DetailsPhysiquePiercingFacial)
router.put("/personnalite/temperament/:id",rencontreController.PersonnaliteTemperament)
router.put("/personnalite/sociabilite/:id",rencontreController.PersonnaliteSociabilite)
router.put("/personnalite/caractere/:id",rencontreController.PersonnaliteCaractere)
router.put("/habitude/rythme/:id",rencontreController.HabitudeRythmeDeSoir)
router.put("/habitude/alcool/:id",rencontreController.HabitudeAlcool)
router.put("/habitude/cigarette/:id",rencontreController.HabitudeCigarette)
router.put("/habitude/regime/:id",rencontreController.HabitudeRegimeAlimentaire)
router.put("/habitude/hobbies/:id",rencontreController.HabitudeHobbies)
router.put("/habitude/musique/:id",rencontreController.HabitudeGoutsMusicaux)
router.get("/libre",rencontreController.getALLProfileLibre)
router.get("/trie/localisation/asc",rencontreController.TrierParLocalisationAutourDeMoiASC)
router.get("/trie/localisation/desc",rencontreController.TrierParLocalisationAutourDeMoiDESC)
router.get("/trie/age/asc",rencontreController.TrierParAgeASC)
router.get("/trie/age/desc",rencontreController.TrierParAgeDESC)
router.get("/trie/inscri/asc",rencontreController.TrierParDateInscriASC)
router.get("/trie/inscri/desc",rencontreController.TrierParDateInscriDESC)
router.get("/:id",rencontreController.RencontreInfo)


module.exports=router;
